### ISSUE TITLE
package-lock.json resolves all dependencies to repo packages.bethel.jw.org

### ISSUE THREAD

**Issue by mrvisser** [yhirose/react-typescript-electron-sample-with-create-react-app-and-electron-builder#20]
Should that be switched back to npmjs? The jw.org one doesn't resolve for me.

**Comment by yhirose** [comment]
@mrvisser, oops... Thanks for finding the mistake! I'll fix it right away.

**Comment by yhirose** [comment]
I just fixed it. Please let me know if your still have the problem with the fix. Thanks!
