### ISSUE TITLE
What is the https://packages.bethel.jw.org in the yarn.lock?

### ISSUE THREAD

**Issue by jonah-saltzman** [yhirose/react-typescript-electron-sample-with-create-react-app-and-electron-builder#37]
NPM & yarn were trying to install React, Electron, and a few other packages from https://packages.bethel.jw.org/ which as far as I can tell is the website of the Jehovah's Witnesses? Deleting yarn.lock and re-running npm-install fixed the issue, figured I'd let you know.

**Comment by yhirose** [comment]
@jonah-saltzman, that's absolutely my mistake... I fixed it as you did. Thank you for finding and reporting it, and sorry for causing the inconvenience. :)

**Comment by jonah-saltzman** [comment]
Haha no worries, thanks for putting the package together, it's great!
