### ISSUE TITLE
× TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by tudiantuan** [yhirose/react-typescript-electron-sample-with-create-react-app-and-electron-builder#7]
<img width="781" alt="Screen Shot 2020-07-10 at 10 15 31" src="https://user-images.githubusercontent.com/39153315/87112529-43681900-c296-11ea-968e-520d0e5d0643.png">

**Comment by yhirose** [comment]
@tudiantuan, thank you for the report. But, I don't find such a problem at all.

**Comment by kunokdev** [comment]
@yhirose  this is common problem when trying to import `ipcRenderer` into React code. 
Seems like this repository doesn't handle/support ipc communication between renderer and main process.

**Comment by yhirose** [comment]
@kunokdev, great! Could you show me the smallest possible code to reproduce it?

**Comment by kunokdev** [comment]
Steps to reproduce:

1. Clone this repo
2. Open any React file, e.g. App.tsx
3. Try to import anything electron related

```

import { ipcRenderer } from "electron";

const App: React.FC = () => {
  console.log(ipcRenderer);
```

This error appears: 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/13220754/100881507-4c0ff480-34ae-11eb-98d1-afebf001cab6.png">


Perhaps changing import to:

```
const ipcRenderer = window.require("electron").ipcRenderer;
```

could solve this problem.

**Comment by yhirose** [comment]
@kunokdev, do you think if it's a problem related to this project, or a typical Electron issue which can happen in any Electron project?

**Comment by kunokdev** [comment]
I'd say It's caused by electron+cra(webpack) combo; Depends how you wanna look at it; this issue affects this repo; but this repo isn't the cause of the issue. You should probably add something in README or code example where renderer (React) process communicates with main (Electron) process.

**Comment by stereosteve** [comment]
To use node modules and code in react, the webpack target needs to be `electron-renderer`.

CRA doesn't make it easy to modify webpack config, options are:

* eject
* add a preload script, and use `window.postMessage` in react code to send message to preload code, and use ipcRenderer from there.  This is described in [this article](https://jaketrent.com/post/select-directory-in-electron/)

**Comment by kunokdev** [comment]
> To use node modules and code in react, the webpack target needs to be `electron-renderer`.
> 
> CRA doesn't make it easy to modify webpack config, options are:
> 
> * eject
> * add a preload script, and use `window.postMessage` in react code to send message to preload code, and use ipcRenderer from there.  This is described in [this article](https://jaketrent.com/post/select-directory-in-electron/)

I am successfully using ipcRenderer without ejecting or preload scripts

**Comment by stereosteve** [comment]
@kunokdev I see that using `window.require("fs")` instead of using `import` works, but all the TypeScript typing is missing.  Is there a way to get the typing for node modules as well?

---

update this seems to work ok:

```ts
import * as FS from "fs";
const fs: typeof FS = window.require("fs");
```

or:

```ts
import { IpcRenderer } from 'electron'
const ipcRenderer: IpcRenderer = window.require('electron').ipcRenderer
```

**Comment by Romex91** [comment]
@stereosteve, `window.require` is an ugly workaround.

There is a better fix:
https://github.com/electron/electron/issues/7300#issuecomment-496006781
